name: latest
on: [push]

env:
  SUBDIR: bob
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        working-directory: ./${{ env.SUBDIR }}
        run: go test
